[package]
authors = ["Kevin R. Stravers"]
name = "program"
version = "0.1.0"

[dependencies]
# foobar = { path = "./foobar" }  # This is how you specify a path
argparse = "0.2.1"
env_logger = "0.3.2"
log = "0.3.5"
rand = "0.3.14"
toml = "0.1.28"
